#! /usr/bin/env python

from libmycurses import *
from PIL import Image
import argparse
import os

VERSION = '1.1'

def main(fig,ctype='default',raw=False):
    res = getdata(fig,raw)
    print 'x=',len(res)
    print 'y=',len(res[0])
    #print res[0][0]
    xsize = len(res)
    ysize = len(res[0])
    clear()
    for i in range(xsize):
        for j in range(ysize):
            c = setcolor(res[i][j],ctype=ctype)
            if ctype=='256_colors':
                put(i*2,j,'  ',BG256(c))
            elif ctype=='default':
                put(i*2,j,'  ',BG[c])

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('fig',help='figure file.',default=' ')
    parser.add_argument('-V','--version',dest='version',help='show version and exit.',action='version',version='%(prog)s '+VERSION)
    parser.add_argument('--raw',help='show fig at raw size',action='store_true')
    #parser.add_argument('--no_curses',help="don't use curses module",action='store_true')
    args = parser.parse_args()

    if os.environ.has_key('TERM') and os.environ['TERM']=='xterm-256color':
        ctype='256_colors'
    else:
        ctype='default'
    main(args.fig,ctype,args.raw)

